#ifndef GPIO_ASSIGNMENTS_H_
#define GPIO_ASSIGNMENTS_H_

// GPIO
#define GPIO_HALL_EFFECT_1 0
#define GPIO_HALL_EFFECT_2 0

#define GPIO_TURN_BUTTON_1 21
#define GPIO_TURN_BUTTON_2 22


#endif // GPIO_ASSIGNMENTS_H_
